name = "Implicit2TetMesh"
uuid = "2ee54d01-0bfe-46b7-bcc9-ff486d194268"
authors = ["jezekon <78500480+jezekon@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
CairoMakie = "0.13.2"
JLD2 = "0.5.11"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
Random = "1.11.0"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
Test = "1.11.0"
WriteVTK = "1.21.1"
